# nmt.yaml

#Basic configuration file. You can add any arguments that would be passed via flags, as 
# described here: https://opennmt.net/OpenNMT-py/ . You can play with different models
# the framework allows you to specify. 

#Fill in TODOs in order to have a minimal complete yaml file

## Where the samples will be written
save_data: #TODO: prefix for saving files  
## Where the vocab(s) will be written
src_vocab: #TODO: vocabulary file for source
tgt_vocab: #TODO: vocubulary file to target  
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus paths
data:
    corpus_1:
        path_src: #TODO source train file
        path_tgt: #TODO target train file 
    valid:
        path_src: #TODO source dev file 
        path_tgt: #TDOO target dev file

# Train on a single GPU
# optimzer hyper-paramenters
world_size: 1
gpu_ranks: [0]
learning_rate: 1
start_decay_steps : 50000 


# Where to save the checkpoints
save_model: # TODO prefix for saivng models
save_checkpoint_steps: 10000
train_steps: 100000
valid_steps: 500

#model parameters 
layers: 2
